# Generated by Django 3.1.2 on 2020-12-26 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('start_bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.ImageField(blank=True, upload_to='images/')),
                ('isActive', models.BooleanField()),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
