# Generated by Django 3.1.2 on 2020-12-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201227_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
