# Generated by Django 3.1.2 on 2020-12-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201231_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='winner',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
